version: '3.9'

services:
    nginx:
        build: ".docker/local/nginx"
        platform: linux/arm64/v8
        container_name: external-server-nginx
        ports:
            - "8081:80"
        volumes:
            - ./public:/app/public
            - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - default
            - shared-network

    app:
        build: ".docker/local/php"
        container_name: external-server-app
        working_dir: /app
        volumes:
            - ".:/app"
            - "./.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        ports:
            - "9003:9000"
        environment:
            - USER_NAME
            - USER_ID
            - GROUP_NAME
            - GROUP_ID
            - OS_NAME
        depends_on:
            - redis
        networks:
            - default
            - shared-network
        extra_hosts:
            - "host.docker.internal:host-gateway"

    init-mysql:
        image: mysql:8.0
        container_name: external-server-init-mysql
        environment:
            MYSQL_ROOT_PASSWORD: $API_SERVER_DB_ROOT_PASSWORD
        volumes:
          - "./.docker/local/scripts/init-external-db.sh:/init-external-db.sh"
        entrypoint: ["/bin/bash", "-c", "chmod +x /init-external-db.sh && /init-external-db.sh"]
        networks:
            - default
            - shared-network
        restart: "no"

    redis:
        image: redis:6.2-buster
        container_name: external-server-redis
        ports:
            - "6380:6379"
        networks:
            - default
            - shared-network

networks:
  shared-network:
    external: true
