name: debug test

on: push

jobs:
  debug-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: external_server_test
          MYSQL_USER: external_server_test
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: external_server_test
      DB_USERNAME: root
      DB_PASSWORD: root
      API_SERVER_DB_HOST: 127.0.0.1
      API_SERVER_DB_PORT: 3306
      API_SERVER_DB_DATABASE: template_server_test
      API_SERVER_DB_USERNAME: root
      API_SERVER_DB_PASSWORD: root
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: pcov

      - name: Cache composer
        id: composer-cache
        run: |
          echo "cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: $${{ steps.composer-cache.outputs.cache-dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-suggest --optimize-autoloader --prefer-dist

      - name: Dump Autoload
        run: composer dump-autoload

      - name: Generate key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate
      
      - name: Checkout template_api_server repository
        uses: actions/checkout@v4
        with:
          repository: yusuke-takatsu/template_api_server
          path: template_api_server
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install (template_api_server)
        run: |
          cd template_api_server
          composer install --no-interaction --prefer-dist

      - name: Key generate (template_api_server)
        run: |
          cd template_api_server
          php artisan key:generate
        
      - name: Migrate template_api_server
        run: |
          cd template_api_server
          php artisan migrate

      - name: Run tests
        run: php artisan test --coverage
